import { Montserrat } from "next/font/google";
import "../globals.css";
import "../normalize.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
const montserrat = Montserrat({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
