import { Montserrat } from "next/font/google";
import "../globals.css";
import "../normalize.css";
import { Providers } from "../providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
const montserrat = Montserrat({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
