import { Inter } from "next/font/google";
import "./globals.css";
import Nav, { FloatingNav } from "@/modules/layout/templates/nav";
import Footer from "@/modules/layout/templates/footer/index";
import { FaHome, FaUser } from "react-icons/fa";
import { FaMessage } from "react-icons/fa6";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navItems = [
  {
    name: "Home",
    link: "/",
    icon: <FaHome className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "About",
    link: "/about",
    icon: <FaUser className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "Contact",
    link: "/contact",
    icon: <FaMessage className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
];
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FloatingNav navItems={navItems} />
        <div className="">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
